#root -l -q -b 'MakeFRFileEE.C("2016")'
#root -l -q -b 'MakeFRFileEE.C("2017")'
#root -l -q -b 'MakeFRFileEE.C("2018")'
root -l -q -b 'MakeFRFileMM.C("2016")'
root -l -q -b 'MakeFRFileMM.C("2017")'
root -l -q -b 'MakeFRFileMM.C("2018")'

#root -l -q -b 'MakeFRFileEE_pt.C("2016")'
#root -l -q -b 'MakeFRFileEE_pt.C("2017")'
#root -l -q -b 'MakeFRFileEE_pt.C("2018")'
root -l -q -b 'MakeFRFileMM_pt.C("2016")'
root -l -q -b 'MakeFRFileMM_pt.C("2017")'
root -l -q -b 'MakeFRFileMM_pt.C("2018")'

#root -l -q -b 'MakeFRFileEEFix.C("2016")'
#root -l -q -b 'MakeFRFileEEFix.C("2017")'
#root -l -q -b 'MakeFRFileEEFix.C("2018")'
root -l -q -b 'MakeFRFileMMFix.C("2016")'
root -l -q -b 'MakeFRFileMMFix.C("2017")'
root -l -q -b 'MakeFRFileMMFix.C("2018")'
