cd /data6/Users/jalmond/2020/HL_SKFlatAnalyzer_ULv3/SKFlatAnalyzer/HNDiLeptonWorskspace/CutFlow/
latex /data6/Users/jalmond/2020/HL_SKFlatAnalyzer_ULv3/SKFlatAnalyzer/HNDiLeptonWorskspace/CutFlow//Cutflow_EMu_RegionPlots_DiLep_PileUpWight.tex
dvipdf /data6/Users/jalmond/2020/HL_SKFlatAnalyzer_ULv3/SKFlatAnalyzer/HNDiLeptonWorskspace/CutFlow//Cutflow_EMu_RegionPlots_DiLep_PileUpWight.dvi
mv /data6/Users/jalmond/2020/HL_SKFlatAnalyzer_ULv3/SKFlatAnalyzer/HNDiLeptonWorskspace/CutFlow//Cutflow_EMu_RegionPlots_DiLep_PileUpWight.pdf  /data6/Users/jalmond/2020/HL_SKFlatAnalyzer_ULv3/SKFlatAnalyzer/HNDiLeptonWorskspace/Output/Plots//Run2UltraLegacy_v3/HNL_Validation/2018//RegionPlots_DiLep_PileUpWight/
rm Cutflow_EMu_RegionPlots_DiLep_PileUpWight.aux
rm Cutflow_EMu_RegionPlots_DiLep_PileUpWight.tex
rm Cutflow_EMu_RegionPlots_DiLep_PileUpWight.dvi
cd -