cd /data6/Users/jalmond/2020/HL_SKFlatAnalyzer_ULv3/SKFlatAnalyzer/HNDiLeptonWorskspace/CutFlow/
latex /data6/Users/jalmond/2020/HL_SKFlatAnalyzer_ULv3/SKFlatAnalyzer/HNDiLeptonWorskspace/CutFlow//Cutflow_EE_RegionPlots_ZPeakTruthMatched_BTagSF.tex
dvipdf /data6/Users/jalmond/2020/HL_SKFlatAnalyzer_ULv3/SKFlatAnalyzer/HNDiLeptonWorskspace/CutFlow//Cutflow_EE_RegionPlots_ZPeakTruthMatched_BTagSF.dvi
mv /data6/Users/jalmond/2020/HL_SKFlatAnalyzer_ULv3/SKFlatAnalyzer/HNDiLeptonWorskspace/CutFlow//Cutflow_EE_RegionPlots_ZPeakTruthMatched_BTagSF.pdf  /data6/Users/jalmond/2020/HL_SKFlatAnalyzer_ULv3/SKFlatAnalyzer/HNDiLeptonWorskspace/Output/Plots//Run2UltraLegacy_v3/HNL_Validation/2018//RegionPlots_ZPeakTruthMatched_BTagSF/
rm Cutflow_EE_RegionPlots_ZPeakTruthMatched_BTagSF.aux
rm Cutflow_EE_RegionPlots_ZPeakTruthMatched_BTagSF.tex
rm Cutflow_EE_RegionPlots_ZPeakTruthMatched_BTagSF.dvi
cd -