cd /data6/Users/jalmond/2020/HL_SKFlatAnalyzer_ULv3/SKFlatAnalyzer/HNDiLeptonWorskspace/CutFlow/
latex /data6/Users/jalmond/2020/HL_SKFlatAnalyzer_ULv3/SKFlatAnalyzer/HNDiLeptonWorskspace/CutFlow//Cutflow_MuMu_RegionPlots_DiLep_TopRW.tex
dvipdf /data6/Users/jalmond/2020/HL_SKFlatAnalyzer_ULv3/SKFlatAnalyzer/HNDiLeptonWorskspace/CutFlow//Cutflow_MuMu_RegionPlots_DiLep_TopRW.dvi
mv /data6/Users/jalmond/2020/HL_SKFlatAnalyzer_ULv3/SKFlatAnalyzer/HNDiLeptonWorskspace/CutFlow//Cutflow_MuMu_RegionPlots_DiLep_TopRW.pdf  /data6/Users/jalmond/2020/HL_SKFlatAnalyzer_ULv3/SKFlatAnalyzer/HNDiLeptonWorskspace/Output/Plots//Run2UltraLegacy_v3/HNL_Validation/2018//RegionPlots_DiLep_TopRW/
rm Cutflow_MuMu_RegionPlots_DiLep_TopRW.aux
rm Cutflow_MuMu_RegionPlots_DiLep_TopRW.tex
rm Cutflow_MuMu_RegionPlots_DiLep_TopRW.dvi
cd -