cd /data6/Users/jalmond/2020/HL_SKFlatAnalyzer_ULv3/SKFlatAnalyzer/HNDiLeptonWorskspace/CutFlow/
latex /data6/Users/jalmond/2020/HL_SKFlatAnalyzer_ULv3/SKFlatAnalyzer/HNDiLeptonWorskspace/CutFlow//Cutflow_MuMu_RegionPlots_DiLep_DYReweight.tex
dvipdf /data6/Users/jalmond/2020/HL_SKFlatAnalyzer_ULv3/SKFlatAnalyzer/HNDiLeptonWorskspace/CutFlow//Cutflow_MuMu_RegionPlots_DiLep_DYReweight.dvi
mv /data6/Users/jalmond/2020/HL_SKFlatAnalyzer_ULv3/SKFlatAnalyzer/HNDiLeptonWorskspace/CutFlow//Cutflow_MuMu_RegionPlots_DiLep_DYReweight.pdf  /data6/Users/jalmond/2020/HL_SKFlatAnalyzer_ULv3/SKFlatAnalyzer/HNDiLeptonWorskspace/Output/Plots//Run2UltraLegacy_v3/HNL_Validation/2018//RegionPlots_DiLep_DYReweight/
rm Cutflow_MuMu_RegionPlots_DiLep_DYReweight.aux
rm Cutflow_MuMu_RegionPlots_DiLep_DYReweight.tex
rm Cutflow_MuMu_RegionPlots_DiLep_DYReweight.dvi
cd -