indiv_bins=2020_09_20_175103__Shape_HN_SR1_2_3_4_EE_MM
combbins=2020_09_20_201318__Shape_HN_SRComb12_EE_MM
combyears=2020_09_20_205948__Shape_HNCombinedYears_SR12_EE_MM
indiv_bins_el=2020_09_23_032223__Shape_HN_SR1_2_3_4_EE_MM
combbins_el=2020_09_23_053926__Shape_HN_SRComb12_EE_MM
combyears_el=2020_09_23_061545__Shape_HNCombinedYears_SR12_EE_MM
indiv_bins_dilep=2020_09_22_040133__Shape_HN_Dilepton_SR1_2_3_4_EE_MM
combbins_dilep=2020_09_22_050401__Shape_HN_Dilepton_SRComb12_EE_MM
combyears_dilep=2020_09_22_101407__Shape_HNCombinedYears_SR12_EE_MM
cd IndividualSRs/
#python readLimitsShape_individualbins_rootfile.py  -c configfiles/config_HNtypeI_JA_individualbins.txt -i $indiv_bins
#python readLimitsShape_individualbins_rootfile.py  -c configfiles/config_HNtypeI_JAEl_individualbins.txt -i $indiv_bins_el
#python readLimitsShape_individualbins_rootfile.py  -c configfiles/config_HNtypeI_Dilepton_individualbins.txt -i $indiv_bins_dilep
cd -
cd CombinedSRs
python readLimitsShape_combinedsrs.py -c configfiles/config_HNtypeI_JA_combinedsrs.txt -i  $combbins
python readLimitsShape_combinedsrs.py -c configfiles/config_HNtypeI_JAEl_combinedsrs.txt  -i $combbins_el
python readLimitsShape_combinedsrs.py -c configfiles/config_HNtypeI_Dilepton_combinedsrs.txt -i $combbins_dilep
cd -
cd CombinedYears
python readLimitsShape_combyears.py  -c configfiles/config_HNtypeI_JA_combinedyears.txt -i $combyears
python readLimitsShape_combyears.py  -c configfiles/config_HNtypeI_JAEl_combinedyears.txt -i $combyears_el
python readLimitsShape_combyears.py  -c configfiles/config_HNtypeI_Dilepton_combinedyears.txt -i $combyears_dilep
cd -
